config/routes.rb
Readingengineer::Application.routes.draw do
  resources :journals

  devise_for :users
  root "journals#index"
  get "about" => "pages#about"
  get "reading" => "pages#reading"
  get "engineering" => "pages#engineering"
  get "others" => "pages#others"
  

  

end

app/models/journal.rb
class Journal < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :journals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @journals = Journal.all
  end

  def show
  end

  def new
    @journal = current_user.journals.build
  end

  def edit
  end

  def create
    @journal = current_user.journals.build(journal_params)
    if @journal.save
      redirect_to @journal, notice: 'Journal was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @journal.update(journal_params)
      redirect_to @journal, notice: 'Journal was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @journal.destroy
    redirect_to journals_url
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    def correct_user
      @journal = current_user.journals.find_by(id: params[:id])
      redirect_to journals_path, notice: "Not authorized to edit this" if @journal.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_params
      params.require(:journal).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/journals/_form.html.erb
<%= form_for(@journal) do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
      <% @journal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
      <%= f.label :body %><br>
      <%= f.text_area :body, :rows => "10", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Editing journal</h1>

<%= render 'form' %>

<%= link_to 'Show', @journal %> |
<%= link_to 'Back', journals_path %>

app/views/journals/index.html.erb
<div id="journals" class="transitions-enabled">
  <% @journals.each do |journal| %>
    <div class="box">
      <div class="penscript-title">
        <%= journal.title %>
      </div>
      <p>
        <%= journal.body[0 .. 200] %>
      </p>
      <%= link_to 'Read More', journal_path(journal), class: "btn btn-default btn-sm" %>
    </div>
  <% end %>
</div>

<% if current_user == User.first %>
  <%= link_to 'New Journal', new_journal_path, class: "btn btn-warning"  %>
<% end %>

app/views/journals/new.html.erb
<%= render 'form' %>

app/views/journals/show.html.erb
<div class="panel panel-default">
  
  <div class="panel-heading">
    <div class="panel-title penscript-title"><%= @journal.title %> <small><%= l @journal.created_at, format: :short %></small></div>
  </div>
  
  <div class="panel-body">
  	  <div class="penscript">
  			<%= @journal.body %>
  		</div>
  </div>
  
  <div class="panel-footer">
  	좋아요
  </div>

</div>

<% if @journal.user == current_user %>
	<%= link_to 'Edit', edit_journal_path(@journal), class: "btn btn-warning" %>
	<%= link_to 'Delete', @journal, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning"  %>
<% end %>
<%= link_to 'Back', journals_path, class: "btn btn-primary"  %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">

  <div class="container">  
    <div class="row">
      <div class="col-md-8">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "reading engineer", root_path, class: "navbar-brand" %> 
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "about me", about_path, class: "navbar-categroy" %></li>
            <li><%= link_to "reading", reading_path, class: "navbar-categroy" %></li>
            <li><%= link_to "engineering", engineering_path, class: "navbar-categroy" %><li>
            <li><%= link_to "others", others_path, class: "navbar-categroy" %></li>
          </ul>
          <ul class="nav navbar-nav">
          <% if user_signed_in? %>        
            <li class="active">
              <%= link_to "click here to log out", destroy_user_session_path, method: :delete, class: "navbar-category" %>
            </li>
            <li class="active">
              <%= link_to "account settings", edit_user_registration_path, class: "navbar-category" %>
            </li>
          <% else %> 
            <li class="active">
              <%= link_to "click here to log in", new_user_session_path, class: "navbar-category" %>
            </li>
            <li class="active">
              <%= link_to "sign up if you want to access more", new_user_registration_path, class: "navbar-category" %>
            </li>
          <% end %>
        </ul>
        </div><!-- /.navbar-collapse -->
 
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>readingengineer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
  <div class="row">
    <div class="col-md-8">
			<% flash.each do |name, msg| %>
		     <%= content_tag(:div, msg, class: "alert alert-info") %>
			<% end %>
	
			<%= yield %>
		</div>
	</div>
</div>

</body>
</html>

app/views/pages/home.html.erb
<div class="penscript"> <p>한글은 이렇게 보이지롱</p> </div>

    <div class="thumbnail">
      <div class="caption">
      	<div class="penscript-title">
	      	<p>그대 입술이</p>
	      </div>
	      <div class="penscript">
	        <p> 그댄 거짓말을 하죠 항상 참을 수가 없죠 이젠 목소리로 알죠 뻔한 말은 그만해요 오늘은 그냥 가줘요 우리 이러는 거 아냐 나를 좀 기다려줘요 근데 ...</p>
      	</div>
        <p><a href="#" class="btn btn-primary" role="button">view more</a></p>
      </div>
    </div>
</div>